-- THIS FILE IS AUTO-GENERATED by scripts/squash-migrations.mjs
-- Last updated: 2026-07-12T13:14:24.930Z
-- Do not edit directly. Keep individual migration files and regenerate this.

-- BEGIN supabase/schema.sql

create table public.profiles (
  id uuid references auth.users on delete cascade primary key,
  updated_at timestamp with time zone,
  full_name text,
  preferred_unit text default 'kg',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table public.exercises (
  id uuid default gen_random_uuid() primary key,
  name text not null,
  target_muscle text not null,
  equipment text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table public.routines (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references public.profiles(id) on delete cascade not null,
  title text not null,
  description text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table public.routine_exercises (
  id uuid default gen_random_uuid() primary key,
  routine_id uuid references public.routines(id) on delete cascade not null,
  exercise_id uuid references public.exercises(id) on delete cascade not null,
  order_index integer not null,
  target_sets integer default 3,
  target_reps text default '10-12',
  notes text
);

create table public.workout_logs (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references public.profiles(id) on delete cascade not null,
  routine_id uuid references public.routines(id) on delete set null,
  start_time timestamp with time zone default timezone('utc'::text, now()) not null,
  end_time timestamp with time zone,
  ai_insight text
);

create table public.set_logs (
  id uuid default gen_random_uuid() primary key,
  workout_log_id uuid references public.workout_logs(id) on delete cascade not null,
  exercise_id uuid references public.exercises(id) on delete cascade not null,
  set_number integer not null,
  weight numeric(5,2) not null,
  reps integer not null,
  rpe integer check (rpe >= 1 and rpe <= 10),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);


-- END supabase/schema.sql

-- BEGIN supabase/migrations/20260705_add_rls_and_routine_persistence.sql

-- Enable Row Level Security and authenticated-user policies for the fitness app.
-- Run this after the initial schema if you already created the original tables.

alter table public.profiles enable row level security;
alter table public.exercises enable row level security;
alter table public.routines enable row level security;
alter table public.routine_exercises enable row level security;
alter table public.workout_logs enable row level security;
alter table public.set_logs enable row level security;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, full_name)
  values (new.id, coalesce(new.raw_user_meta_data->>'full_name', new.email))
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

drop policy if exists "Users can read own profile" on public.profiles;
create policy "Users can read own profile"
on public.profiles for select
to authenticated
using (auth.uid() = id);

drop policy if exists "Users can update own profile" on public.profiles;
create policy "Users can update own profile"
on public.profiles for update
to authenticated
using (auth.uid() = id)
with check (auth.uid() = id);

drop policy if exists "Exercises are readable by authenticated users" on public.exercises;
create policy "Exercises are readable by authenticated users"
on public.exercises for select
to authenticated
using (true);

drop policy if exists "Authenticated users can create exercises" on public.exercises;
create policy "Authenticated users can create exercises"
on public.exercises for insert
to authenticated
with check (true);

drop policy if exists "Users can read own routines" on public.routines;
create policy "Users can read own routines"
on public.routines for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "Users can create own routines" on public.routines;
create policy "Users can create own routines"
on public.routines for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "Users can update own routines" on public.routines;
create policy "Users can update own routines"
on public.routines for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "Users can delete own routines" on public.routines;
create policy "Users can delete own routines"
on public.routines for delete
to authenticated
using (auth.uid() = user_id);

drop policy if exists "Users can read exercises from own routines" on public.routine_exercises;
create policy "Users can read exercises from own routines"
on public.routine_exercises for select
to authenticated
using (
  exists (
    select 1 from public.routines
    where routines.id = routine_exercises.routine_id
      and routines.user_id = auth.uid()
  )
);

drop policy if exists "Users can create exercises in own routines" on public.routine_exercises;
create policy "Users can create exercises in own routines"
on public.routine_exercises for insert
to authenticated
with check (
  exists (
    select 1 from public.routines
    where routines.id = routine_exercises.routine_id
      and routines.user_id = auth.uid()
  )
);

drop policy if exists "Users can manage exercises in own routines" on public.routine_exercises;
create policy "Users can manage exercises in own routines"
on public.routine_exercises for update
to authenticated
using (
  exists (
    select 1 from public.routines
    where routines.id = routine_exercises.routine_id
      and routines.user_id = auth.uid()
  )
)
with check (
  exists (
    select 1 from public.routines
    where routines.id = routine_exercises.routine_id
      and routines.user_id = auth.uid()
  )
);

drop policy if exists "Users can delete exercises in own routines" on public.routine_exercises;
create policy "Users can delete exercises in own routines"
on public.routine_exercises for delete
to authenticated
using (
  exists (
    select 1 from public.routines
    where routines.id = routine_exercises.routine_id
      and routines.user_id = auth.uid()
  )
);

drop policy if exists "Users can read own workout logs" on public.workout_logs;
create policy "Users can read own workout logs"
on public.workout_logs for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "Users can create own workout logs" on public.workout_logs;
create policy "Users can create own workout logs"
on public.workout_logs for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "Users can update own workout logs" on public.workout_logs;
create policy "Users can update own workout logs"
on public.workout_logs for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "Users can read own set logs" on public.set_logs;
create policy "Users can read own set logs"
on public.set_logs for select
to authenticated
using (
  exists (
    select 1 from public.workout_logs
    where workout_logs.id = set_logs.workout_log_id
      and workout_logs.user_id = auth.uid()
  )
);

drop policy if exists "Users can create own set logs" on public.set_logs;
create policy "Users can create own set logs"
on public.set_logs for insert
to authenticated
with check (
  exists (
    select 1 from public.workout_logs
    where workout_logs.id = set_logs.workout_log_id
      and workout_logs.user_id = auth.uid()
  )
);


-- END supabase/migrations/20260705_add_rls_and_routine_persistence.sql

-- BEGIN supabase/migrations/20260705_harden_exercise_deduplication.sql

-- Harden exercise persistence by deduplicating existing rows and preventing future duplicates.
-- Run after 20260705_add_rls_and_routine_persistence.sql.

begin;

-- Repoint routine_exercises to a canonical exercise per normalized name/muscle/equipment.
with ranked_exercises as (
  select
    id,
    first_value(id) over (
      partition by lower(btrim(name)), lower(btrim(target_muscle)), lower(btrim(equipment))
      order by id::text
    ) as canonical_id
  from public.exercises
)
update public.routine_exercises re
set exercise_id = ranked_exercises.canonical_id
from ranked_exercises
where re.exercise_id = ranked_exercises.id
  and ranked_exercises.id <> ranked_exercises.canonical_id;

-- Repoint historical set_logs to the same canonical exercise.
with ranked_exercises as (
  select
    id,
    first_value(id) over (
      partition by lower(btrim(name)), lower(btrim(target_muscle)), lower(btrim(equipment))
      order by id::text
    ) as canonical_id
  from public.exercises
)
update public.set_logs sl
set exercise_id = ranked_exercises.canonical_id
from ranked_exercises
where sl.exercise_id = ranked_exercises.id
  and ranked_exercises.id <> ranked_exercises.canonical_id;

-- Delete duplicate exercise rows once references point to canonical rows.
with ranked_exercises as (
  select
    id,
    row_number() over (
      partition by lower(btrim(name)), lower(btrim(target_muscle)), lower(btrim(equipment))
      order by id::text
    ) as duplicate_rank
  from public.exercises
)
delete from public.exercises e
using ranked_exercises
where e.id = ranked_exercises.id
  and ranked_exercises.duplicate_rank > 1;

-- Enforce normalized uniqueness for future inserts.
create unique index if not exists exercises_normalized_identity_idx
on public.exercises (
  lower(btrim(name)),
  lower(btrim(target_muscle)),
  lower(btrim(equipment))
);

-- Add supporting indexes for the most common app queries.
create index if not exists routine_exercises_routine_id_idx
on public.routine_exercises (routine_id);

create index if not exists routine_exercises_exercise_id_idx
on public.routine_exercises (exercise_id);

create index if not exists workout_logs_user_start_time_idx
on public.workout_logs (user_id, start_time desc);

create index if not exists set_logs_workout_log_id_idx
on public.set_logs (workout_log_id);

create index if not exists set_logs_exercise_id_idx
on public.set_logs (exercise_id);

commit;


-- END supabase/migrations/20260705_harden_exercise_deduplication.sql

-- BEGIN supabase/migrations/20260706_consolidate_save_routine_rpc.sql

-- Consolidates the same-day rewrites of the routine-saving RPC into one canonical,
-- idempotent migration. Replaces (and supersedes):
--   - 20260705_save_ai_routine_rpc.sql
--   - 20260705_atomic_routine_save.sql
--   - 20260705_save_routine_transaction.sql
-- Those three files rewrote public.save_routine_with_exercises / public.save_ai_routine
-- three times on the same day with drifting signatures. This migration reflects the
-- final, correct state (equivalent to 20260705_save_routine_transaction.sql) and is
-- safe to run regardless of which of the three prior migrations already ran in a given
-- environment: it drops any known prior signature before recreating the functions, since
-- PostgreSQL does not allow CREATE OR REPLACE FUNCTION to rename input parameters.
-- Requires the exercises_normalized_identity_idx unique index from
-- 20260705_harden_exercise_deduplication.sql.

begin;

drop function if exists public.save_routine_with_exercises(text, text, jsonb);
drop function if exists public.save_ai_routine(jsonb);

create function public.save_routine_with_exercises(
  routine_title text,
  routine_description text,
  exercises_payload jsonb
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  new_routine_id uuid;
  exercise_payload jsonb;
  exercise_id uuid;
  exercise_name text;
  exercise_target_muscle text;
  exercise_equipment text;
  exercise_order integer := 0;
  current_user_id uuid := auth.uid();
begin
  if current_user_id is null then
    raise exception 'Debe iniciar sesión para guardar rutinas.';
  end if;

  if routine_title is null or btrim(routine_title) = '' then
    raise exception 'El título de la rutina es obligatorio.';
  end if;

  if exercises_payload is null or jsonb_typeof(exercises_payload) <> 'array' or jsonb_array_length(exercises_payload) = 0 then
    raise exception 'La rutina debe incluir al menos un ejercicio.';
  end if;

  insert into public.routines (user_id, title, description)
  values (current_user_id, btrim(routine_title), nullif(btrim(coalesce(routine_description, '')), ''))
  returning id into new_routine_id;

  for exercise_payload in select value from jsonb_array_elements(exercises_payload)
  loop
    exercise_order := exercise_order + 1;
    exercise_name := btrim(coalesce(exercise_payload->>'name', ''));
    exercise_target_muscle := btrim(coalesce(exercise_payload->>'targetMuscle', ''));
    exercise_equipment := btrim(coalesce(exercise_payload->>'equipment', ''));

    if exercise_name = '' then
      raise exception 'El ejercicio % no tiene nombre.', exercise_order;
    end if;

    select id into exercise_id
    from public.exercises
    where lower(btrim(name)) = lower(btrim(exercise_name))
      and lower(btrim(target_muscle)) = lower(btrim(exercise_target_muscle))
      and lower(btrim(equipment)) = lower(btrim(exercise_equipment))
    limit 1;

    if exercise_id is null then
      begin
        insert into public.exercises (name, target_muscle, equipment)
        values (exercise_name, exercise_target_muscle, exercise_equipment)
        returning id into exercise_id;
      exception when unique_violation then
        select id into exercise_id
        from public.exercises
        where lower(btrim(name)) = lower(btrim(exercise_name))
          and lower(btrim(target_muscle)) = lower(btrim(exercise_target_muscle))
          and lower(btrim(equipment)) = lower(btrim(exercise_equipment))
        limit 1;
      end;
    end if;

    if exercise_id is null then
      raise exception 'No se pudo crear o reutilizar el ejercicio %.', exercise_name;
    end if;

    insert into public.routine_exercises (
      routine_id,
      exercise_id,
      order_index,
      target_sets,
      target_reps,
      notes
    )
    values (
      new_routine_id,
      exercise_id,
      coalesce((exercise_payload->>'orderIndex')::integer, exercise_order),
      nullif(exercise_payload->>'targetSets', '')::integer,
      nullif(exercise_payload->>'targetReps', ''),
      nullif(exercise_payload->>'notes', '')
    );
  end loop;

  return new_routine_id;
end;
$$;

-- Compatibility wrapper for the current dashboard payload shape (Spanish keys from Gemini).
create function public.save_ai_routine(p_routine jsonb)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  exercises_payload jsonb;
begin
  if p_routine is null or jsonb_typeof(p_routine) <> 'object' then
    raise exception 'Payload de rutina inválido.';
  end if;

  select coalesce(jsonb_agg(
    jsonb_build_object(
      'orderIndex', exercise_order,
      'name', btrim(coalesce(exercise_item->>'nombre', '')),
      'targetMuscle', btrim(coalesce(exercise_item->>'musculoObjetivo', '')),
      'equipment', btrim(coalesce(exercise_item->>'equipamiento', '')),
      'targetSets', exercise_item->>'seriesObjetivo',
      'targetReps', exercise_item->>'repeticionesObjetivo',
      'notes', exercise_item->>'notas'
    )
  ), '[]'::jsonb)
  into exercises_payload
  from jsonb_array_elements(coalesce(p_routine->'ejercicios', '[]'::jsonb))
  with ordinality as payload(exercise_item, exercise_order);

  return public.save_routine_with_exercises(
    p_routine->>'titulo',
    p_routine->>'descripcion',
    exercises_payload
  );
end;
$$;

grant execute on function public.save_routine_with_exercises(text, text, jsonb) to authenticated;
grant execute on function public.save_ai_routine(jsonb) to authenticated;

commit;


-- END supabase/migrations/20260706_consolidate_save_routine_rpc.sql

-- BEGIN supabase/migrations/20260706_harden_workout_logs_routine_ownership.sql

-- RLS edge case: the insert/update policies on workout_logs only checked
-- `auth.uid() = user_id`, never that `routine_id` (when set) actually belongs to
-- that same user. A client could bypass the UI and directly call
-- `supabase.from('workout_logs').insert/update({ user_id: me, routine_id: <someone
-- else's routine id> })`. This doesn't leak the other routine's data (routines and
-- routine_exercises stay scoped to their owner via their own RLS), but it lets a
-- user misattribute a workout to a routine they don't own. Tightened both policies
-- to require routine_id to be null or owned by auth.uid(), mirroring the check
-- routine_exercises already does for its own routine_id.

begin;

drop policy if exists "Users can create own workout logs" on public.workout_logs;
create policy "Users can create own workout logs"
on public.workout_logs for insert
to authenticated
with check (
  auth.uid() = user_id
  and (
    routine_id is null
    or exists (
      select 1 from public.routines
      where routines.id = workout_logs.routine_id
        and routines.user_id = auth.uid()
    )
  )
);

drop policy if exists "Users can update own workout logs" on public.workout_logs;
create policy "Users can update own workout logs"
on public.workout_logs for update
to authenticated
using (auth.uid() = user_id)
with check (
  auth.uid() = user_id
  and (
    routine_id is null
    or exists (
      select 1 from public.routines
      where routines.id = workout_logs.routine_id
        and routines.user_id = auth.uid()
    )
  )
);

commit;


-- END supabase/migrations/20260706_harden_workout_logs_routine_ownership.sql

-- BEGIN supabase/migrations/20260706_restrict_direct_exercise_inserts.sql

-- Follow-up to the RLS review (20260706_harden_workout_logs_routine_ownership.sql),
-- which flagged that `exercises` allowed any authenticated user to insert directly
-- (`with check (true)`), bypassing the RPC's name/muscle/equipment normalization and
-- dedup. That was load-bearing for the client-side legacy fallback in
-- guardarRutinaLegacy() (src/app/page.tsx). That fallback is gone now that routine
-- saving goes through POST /api/routines/save, which always calls the
-- security-definer save_ai_routine RPC (bypassing RLS on its own, by design) — no
-- client code inserts into `exercises` directly anymore. Deny direct inserts.

begin;

drop policy if exists "Authenticated users can create exercises" on public.exercises;

commit;


-- END supabase/migrations/20260706_restrict_direct_exercise_inserts.sql

-- BEGIN supabase/migrations/20260706_separate_global_and_personal_exercises.sql

-- Lays the schema groundwork to distinguish global (curated, shared) exercises from
-- personal ones, per the Fase 6 roadmap item. No feature currently creates personal
-- exercises — save_ai_routine still only creates global rows (owner_id null) — so this
-- migration is behavior-preserving for the app as it exists today. It just makes room
-- for a future "add your own exercise" feature without a schema change at that point.
--
-- owner_id null = global/curated, visible to everyone (today's behavior for all rows).
-- owner_id set = personal, visible only to its owner.

begin;

alter table public.exercises
  add column if not exists owner_id uuid references auth.users(id) on delete cascade;

-- Replace the single global unique index with two partial ones, scoped by ownership.
-- A plain `unique (owner_id, name, muscle, equipment)` would silently stop deduplicating
-- global rows, because Postgres never considers NULL = NULL for uniqueness purposes.
drop index if exists public.exercises_normalized_identity_idx;

create unique index if not exists exercises_normalized_identity_global_idx
on public.exercises (
  lower(btrim(name)),
  lower(btrim(target_muscle)),
  lower(btrim(equipment))
)
where owner_id is null;

create unique index if not exists exercises_normalized_identity_personal_idx
on public.exercises (
  owner_id,
  lower(btrim(name)),
  lower(btrim(target_muscle)),
  lower(btrim(equipment))
)
where owner_id is not null;

drop policy if exists "Exercises are readable by authenticated users" on public.exercises;
create policy "Exercises are readable by authenticated users"
on public.exercises for select
to authenticated
using (owner_id is null or owner_id = auth.uid());

commit;


-- END supabase/migrations/20260706_separate_global_and_personal_exercises.sql

-- BEGIN supabase/migrations/20260707_add_persistent_profile_fields.sql

-- Persistent user profile fields (Fase 8): objetivo, lesiones/restricciones,
-- equipo disponible y nivel de experiencia, so generar-rutina can read the user's
-- real, persistent preferences instead of relying only on whatever they retype into
-- the per-generation form. This is where the actual fix for the Fase 0 bug lives —
-- Fase 0 only stopped the system prompt from injecting someone else's hardcoded
-- preferences; this is what lets a user's own preferences persist across sessions.
--
-- All nullable: an unfilled profile changes nothing about today's behavior.
-- training_goal/experience_level/equipment_available are constrained to a fixed list
-- (mirrored in src/lib/profileOptions.ts) since they're picked from a dropdown, not
-- freely typed. injury_notes stays free text — restrictions can't be enumerated.

alter table public.profiles
  add column if not exists training_goal text,
  add column if not exists injury_notes text,
  add column if not exists equipment_available text,
  add column if not exists experience_level text;

alter table public.profiles
  drop constraint if exists profiles_training_goal_check,
  add constraint profiles_training_goal_check check (
    training_goal is null or training_goal in (
      'Hipertrofia', 'Fuerza', 'Resistencia', 'Pérdida de grasa', 'Recomposición corporal'
    )
  );

alter table public.profiles
  drop constraint if exists profiles_experience_level_check,
  add constraint profiles_experience_level_check check (
    experience_level is null or experience_level in ('Principiante', 'Intermedio', 'Avanzado')
  );

alter table public.profiles
  drop constraint if exists profiles_equipment_available_check,
  add constraint profiles_equipment_available_check check (
    equipment_available is null or equipment_available in (
      'Gimnasio completo', 'Mancuernas y banca en casa', 'Solo peso corporal', 'Bandas de resistencia'
    )
  );


-- END supabase/migrations/20260707_add_persistent_profile_fields.sql

-- BEGIN supabase/migrations/20260707_add_set_logs_warmup_flag.sql

-- Adds a warmup flag to set_logs so warmup sets can be logged without contaminating
-- volume, estimated 1RM, or average-RPE calculations (which today can't tell a warmup
-- set from a working set). Defaults to false so existing rows keep counting as they
-- always have.

alter table public.set_logs
  add column if not exists is_warmup boolean not null default false;


-- END supabase/migrations/20260707_add_set_logs_warmup_flag.sql

-- BEGIN supabase/migrations/20260707_allow_half_point_rpe.sql

-- Allows half-point RPE (7.5, 8.5, ...) instead of only whole numbers 1-10, so a set
-- logged as "a little harder than an 8 but not quite a 9" doesn't have to round either
-- way. rpe stays nullable; the check now restricts it to 1-10 in 0.5 increments.

alter table public.set_logs
  drop constraint if exists set_logs_rpe_check;

alter table public.set_logs
  alter column rpe type numeric(3,1) using rpe::numeric(3,1);

alter table public.set_logs
  add constraint set_logs_rpe_check check (
    rpe is null or (rpe >= 1 and rpe <= 10 and (rpe * 2) = trunc(rpe * 2))
  );


-- END supabase/migrations/20260707_allow_half_point_rpe.sql

-- BEGIN supabase/migrations/20260707_standardize_exercise_taxonomy.sql

-- Standardizes exercises.target_muscle and exercises.equipment to a fixed taxonomy
-- (mirrored in src/lib/exerciseTaxonomy.ts and the generar-rutina Gemini schema), so
-- volume-by-muscle-group aggregation (Fase 8 "features visibles") can rely on exact
-- matches instead of free text ("Pecho" vs "pecho" vs "Pectoral" never grouping
-- together reliably).
--
-- Canonical muscle groups: Pecho, Espalda, Hombro, Bíceps, Tríceps, Antebrazo,
-- Cuádriceps, Isquiotibiales, Glúteo, Pantorrilla, Core, Trapecio, General (fallback).
-- Canonical equipment: Polea, Barra, Máquina, Mancuerna, Corporal, Otro (fallback).
--
-- Existing free-text values are normalized via a synonym map before the CHECK
-- constraints are added. Anything unrecognized falls back to General/Otro, matching
-- the fallback values save_routine_with_exercises already used before this migration.
--
-- Normalizing text can make previously-distinct rows collide (e.g. "Dorsal" and
-- "Espalda" for the same exercise name both becoming "Espalda"), which would violate
-- the case-insensitive unique indexes from Fase 6. So: drop those indexes, normalize,
-- re-run the Fase 0 exercise-deduplication logic to merge any new collisions, then
-- recreate the indexes.

begin;

drop index if exists public.exercises_normalized_identity_global_idx;
drop index if exists public.exercises_normalized_identity_personal_idx;

update public.exercises
set target_muscle = case lower(btrim(target_muscle))
  when 'pecho' then 'Pecho'
  when 'pectoral' then 'Pecho'
  when 'pectorales' then 'Pecho'
  when 'espalda' then 'Espalda'
  when 'dorsal' then 'Espalda'
  when 'dorsales' then 'Espalda'
  when 'dorso' then 'Espalda'
  when 'hombro' then 'Hombro'
  when 'hombros' then 'Hombro'
  when 'deltoide' then 'Hombro'
  when 'deltoides' then 'Hombro'
  when 'biceps' then 'Bíceps'
  when 'bíceps' then 'Bíceps'
  when 'triceps' then 'Tríceps'
  when 'tríceps' then 'Tríceps'
  when 'antebrazo' then 'Antebrazo'
  when 'antebrazos' then 'Antebrazo'
  when 'cuadriceps' then 'Cuádriceps'
  when 'cuádriceps' then 'Cuádriceps'
  when 'cuadricep' then 'Cuádriceps'
  when 'pierna' then 'Cuádriceps'
  when 'piernas' then 'Cuádriceps'
  when 'isquios' then 'Isquiotibiales'
  when 'isquiotibial' then 'Isquiotibiales'
  when 'isquiotibiales' then 'Isquiotibiales'
  when 'femoral' then 'Isquiotibiales'
  when 'femorales' then 'Isquiotibiales'
  when 'gluteo' then 'Glúteo'
  when 'glúteo' then 'Glúteo'
  when 'gluteos' then 'Glúteo'
  when 'glúteos' then 'Glúteo'
  when 'pantorrilla' then 'Pantorrilla'
  when 'pantorrillas' then 'Pantorrilla'
  when 'gemelo' then 'Pantorrilla'
  when 'gemelos' then 'Pantorrilla'
  when 'core' then 'Core'
  when 'abdomen' then 'Core'
  when 'abdominales' then 'Core'
  when 'abs' then 'Core'
  when 'trapecio' then 'Trapecio'
  when 'trapecios' then 'Trapecio'
  when 'general' then 'General'
  else 'General'
end;

update public.exercises
set equipment = case lower(btrim(equipment))
  when 'polea' then 'Polea'
  when 'poleas' then 'Polea'
  when 'barra' then 'Barra'
  when 'barras' then 'Barra'
  when 'maquina' then 'Máquina'
  when 'máquina' then 'Máquina'
  when 'maquinas' then 'Máquina'
  when 'máquinas' then 'Máquina'
  when 'mancuerna' then 'Mancuerna'
  when 'mancuernas' then 'Mancuerna'
  when 'corporal' then 'Corporal'
  when 'peso corporal' then 'Corporal'
  when 'cuerpo' then 'Corporal'
  when 'otro' then 'Otro'
  when 'otros' then 'Otro'
  else 'Otro'
end;

-- Re-run the Fase 0 exercise-deduplication logic: repoint references to a canonical
-- row per normalized name/muscle/equipment, then delete the now-redundant duplicates.
with ranked_exercises as (
  select
    id,
    first_value(id) over (
      partition by lower(btrim(name)), lower(btrim(target_muscle)), lower(btrim(equipment))
      order by id::text
    ) as canonical_id
  from public.exercises
)
update public.routine_exercises re
set exercise_id = ranked_exercises.canonical_id
from ranked_exercises
where re.exercise_id = ranked_exercises.id
  and ranked_exercises.id <> ranked_exercises.canonical_id;

with ranked_exercises as (
  select
    id,
    first_value(id) over (
      partition by lower(btrim(name)), lower(btrim(target_muscle)), lower(btrim(equipment))
      order by id::text
    ) as canonical_id
  from public.exercises
)
update public.set_logs sl
set exercise_id = ranked_exercises.canonical_id
from ranked_exercises
where sl.exercise_id = ranked_exercises.id
  and ranked_exercises.id <> ranked_exercises.canonical_id;

with ranked_exercises as (
  select
    id,
    row_number() over (
      partition by lower(btrim(name)), lower(btrim(target_muscle)), lower(btrim(equipment))
      order by id::text
    ) as duplicate_rank
  from public.exercises
)
delete from public.exercises e
using ranked_exercises
where e.id = ranked_exercises.id
  and ranked_exercises.duplicate_rank > 1;

create unique index if not exists exercises_normalized_identity_global_idx
on public.exercises (
  lower(btrim(name)),
  lower(btrim(target_muscle)),
  lower(btrim(equipment))
)
where owner_id is null;

create unique index if not exists exercises_normalized_identity_personal_idx
on public.exercises (
  owner_id,
  lower(btrim(name)),
  lower(btrim(target_muscle)),
  lower(btrim(equipment))
)
where owner_id is not null;

alter table public.exercises
  drop constraint if exists exercises_target_muscle_check,
  add constraint exercises_target_muscle_check check (
    target_muscle in (
      'Pecho', 'Espalda', 'Hombro', 'Bíceps', 'Tríceps', 'Antebrazo',
      'Cuádriceps', 'Isquiotibiales', 'Glúteo', 'Pantorrilla', 'Core', 'Trapecio', 'General'
    )
  );

alter table public.exercises
  drop constraint if exists exercises_equipment_check,
  add constraint exercises_equipment_check check (
    equipment in ('Polea', 'Barra', 'Máquina', 'Mancuerna', 'Corporal', 'Otro')
  );

-- Defensively normalize incoming muscle/equipment text the same way, so the RPC
-- stays correct even if a caller ever sends something outside the Gemini schema's enum.
create or replace function public.save_routine_with_exercises(
  routine_title text,
  routine_description text,
  exercises_payload jsonb
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  new_routine_id uuid;
  exercise_payload jsonb;
  exercise_id uuid;
  exercise_name text;
  exercise_target_muscle text;
  exercise_equipment text;
  exercise_order integer := 0;
  current_user_id uuid := auth.uid();
begin
  if current_user_id is null then
    raise exception 'Debe iniciar sesión para guardar rutinas.';
  end if;

  if routine_title is null or btrim(routine_title) = '' then
    raise exception 'El título de la rutina es obligatorio.';
  end if;

  if exercises_payload is null or jsonb_typeof(exercises_payload) <> 'array' or jsonb_array_length(exercises_payload) = 0 then
    raise exception 'La rutina debe incluir al menos un ejercicio.';
  end if;

  insert into public.routines (user_id, title, description)
  values (current_user_id, btrim(routine_title), nullif(btrim(coalesce(routine_description, '')), ''))
  returning id into new_routine_id;

  for exercise_payload in select value from jsonb_array_elements(exercises_payload)
  loop
    exercise_order := exercise_order + 1;
    exercise_name := btrim(coalesce(exercise_payload->>'name', ''));
    exercise_target_muscle := case lower(btrim(coalesce(exercise_payload->>'targetMuscle', '')))
      when 'pecho' then 'Pecho'
      when 'pectoral' then 'Pecho'
      when 'pectorales' then 'Pecho'
      when 'espalda' then 'Espalda'
      when 'dorsal' then 'Espalda'
      when 'dorsales' then 'Espalda'
      when 'dorso' then 'Espalda'
      when 'hombro' then 'Hombro'
      when 'hombros' then 'Hombro'
      when 'deltoide' then 'Hombro'
      when 'deltoides' then 'Hombro'
      when 'biceps' then 'Bíceps'
      when 'bíceps' then 'Bíceps'
      when 'triceps' then 'Tríceps'
      when 'tríceps' then 'Tríceps'
      when 'antebrazo' then 'Antebrazo'
      when 'antebrazos' then 'Antebrazo'
      when 'cuadriceps' then 'Cuádriceps'
      when 'cuádriceps' then 'Cuádriceps'
      when 'cuadricep' then 'Cuádriceps'
      when 'pierna' then 'Cuádriceps'
      when 'piernas' then 'Cuádriceps'
      when 'isquios' then 'Isquiotibiales'
      when 'isquiotibial' then 'Isquiotibiales'
      when 'isquiotibiales' then 'Isquiotibiales'
      when 'femoral' then 'Isquiotibiales'
      when 'femorales' then 'Isquiotibiales'
      when 'gluteo' then 'Glúteo'
      when 'glúteo' then 'Glúteo'
      when 'gluteos' then 'Glúteo'
      when 'glúteos' then 'Glúteo'
      when 'pantorrilla' then 'Pantorrilla'
      when 'pantorrillas' then 'Pantorrilla'
      when 'gemelo' then 'Pantorrilla'
      when 'gemelos' then 'Pantorrilla'
      when 'core' then 'Core'
      when 'abdomen' then 'Core'
      when 'abdominales' then 'Core'
      when 'abs' then 'Core'
      when 'trapecio' then 'Trapecio'
      when 'trapecios' then 'Trapecio'
      when 'general' then 'General'
      else 'General'
    end;
    exercise_equipment := case lower(btrim(coalesce(exercise_payload->>'equipment', '')))
      when 'polea' then 'Polea'
      when 'poleas' then 'Polea'
      when 'barra' then 'Barra'
      when 'barras' then 'Barra'
      when 'maquina' then 'Máquina'
      when 'máquina' then 'Máquina'
      when 'maquinas' then 'Máquina'
      when 'máquinas' then 'Máquina'
      when 'mancuerna' then 'Mancuerna'
      when 'mancuernas' then 'Mancuerna'
      when 'corporal' then 'Corporal'
      when 'peso corporal' then 'Corporal'
      when 'cuerpo' then 'Corporal'
      when 'otro' then 'Otro'
      when 'otros' then 'Otro'
      else 'Otro'
    end;
    if exercise_name = '' then
      raise exception 'El ejercicio % no tiene nombre.', exercise_order;
    end if;

    select id into exercise_id
    from public.exercises
    where lower(btrim(name)) = lower(btrim(exercise_name))
      and lower(btrim(target_muscle)) = lower(btrim(exercise_target_muscle))
      and lower(btrim(equipment)) = lower(btrim(exercise_equipment))
      and owner_id is null
    limit 1;

    if exercise_id is null then
      begin
        insert into public.exercises (name, target_muscle, equipment)
        values (exercise_name, exercise_target_muscle, exercise_equipment)
        returning id into exercise_id;
      exception when unique_violation then
        select id into exercise_id
        from public.exercises
        where lower(btrim(name)) = lower(btrim(exercise_name))
          and lower(btrim(target_muscle)) = lower(btrim(exercise_target_muscle))
          and lower(btrim(equipment)) = lower(btrim(exercise_equipment))
          and owner_id is null
        limit 1;
      end;
    end if;

    if exercise_id is null then
      raise exception 'No se pudo crear o reutilizar el ejercicio %.', exercise_name;
    end if;

    insert into public.routine_exercises (
      routine_id,
      exercise_id,
      order_index,
      target_sets,
      target_reps,
      notes
    )
    values (
      new_routine_id,
      exercise_id,
      coalesce((exercise_payload->>'orderIndex')::integer, exercise_order),
      nullif(exercise_payload->>'targetSets', '')::integer,
      nullif(exercise_payload->>'targetReps', ''),
      nullif(exercise_payload->>'notes', '')
    );
  end loop;

  return new_routine_id;
end;
$$;

commit;


-- END supabase/migrations/20260707_standardize_exercise_taxonomy.sql

-- BEGIN supabase/migrations/20260708_add_body_measurements.sql

-- Body weight / measurements tracking (Fase 8 "features visibles"): no table existed
-- for this at all. One row per log entry, not one row per day, so a user can correct
-- a same-day entry by adding a new one rather than needing an upsert.

create table if not exists public.body_measurements (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references public.profiles(id) on delete cascade not null,
  recorded_at date not null default current_date,
  weight_kg numeric(5,2) not null,
  body_fat_percentage numeric(4,1),
  notes text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create index if not exists body_measurements_user_recorded_at_idx
on public.body_measurements (user_id, recorded_at desc);

alter table public.body_measurements enable row level security;

drop policy if exists "Users can read own body measurements" on public.body_measurements;
create policy "Users can read own body measurements"
on public.body_measurements for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "Users can create own body measurements" on public.body_measurements;
create policy "Users can create own body measurements"
on public.body_measurements for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "Users can update own body measurements" on public.body_measurements;
create policy "Users can update own body measurements"
on public.body_measurements for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "Users can delete own body measurements" on public.body_measurements;
create policy "Users can delete own body measurements"
on public.body_measurements for delete
to authenticated
using (auth.uid() = user_id);


-- END supabase/migrations/20260708_add_body_measurements.sql

-- BEGIN supabase/migrations/20260709_regenerate_routine_day_rpc.sql

-- Lets a user regenerate a single saved routine with AI, in place: same routine id
-- (so /entrenar/[routineId] links and workout_logs.routine_id stay valid), new title/
-- description/exercises. Extracts the per-exercise dedup-insert loop that
-- save_routine_with_exercises (20260706_consolidate_save_routine_rpc.sql) already had
-- inlined into a shared helper so this doesn't have to duplicate it.

begin;

drop function if exists public.save_routine_with_exercises(text, text, jsonb);
drop function if exists public._insert_routine_exercises(uuid, jsonb);

create function public._insert_routine_exercises(
  target_routine_id uuid,
  exercises_payload jsonb
)
returns void
language plpgsql
set search_path = public
as $$
declare
  exercise_payload jsonb;
  exercise_id uuid;
  exercise_name text;
  exercise_target_muscle text;
  exercise_equipment text;
  exercise_order integer := 0;
begin
  if exercises_payload is null or jsonb_typeof(exercises_payload) <> 'array' or jsonb_array_length(exercises_payload) = 0 then
    raise exception 'La rutina debe incluir al menos un ejercicio.';
  end if;

  for exercise_payload in select value from jsonb_array_elements(exercises_payload)
  loop
    exercise_order := exercise_order + 1;
    exercise_name := btrim(coalesce(exercise_payload->>'name', ''));
    exercise_target_muscle := btrim(coalesce(exercise_payload->>'targetMuscle', ''));
    exercise_equipment := btrim(coalesce(exercise_payload->>'equipment', ''));

    if exercise_name = '' then
      raise exception 'El ejercicio % no tiene nombre.', exercise_order;
    end if;

    select id into exercise_id
    from public.exercises
    where lower(btrim(name)) = lower(btrim(exercise_name))
      and lower(btrim(target_muscle)) = lower(btrim(exercise_target_muscle))
      and lower(btrim(equipment)) = lower(btrim(exercise_equipment))
    limit 1;

    if exercise_id is null then
      begin
        insert into public.exercises (name, target_muscle, equipment)
        values (exercise_name, exercise_target_muscle, exercise_equipment)
        returning id into exercise_id;
      exception when unique_violation then
        select id into exercise_id
        from public.exercises
        where lower(btrim(name)) = lower(btrim(exercise_name))
          and lower(btrim(target_muscle)) = lower(btrim(exercise_target_muscle))
          and lower(btrim(equipment)) = lower(btrim(exercise_equipment))
        limit 1;
      end;
    end if;

    if exercise_id is null then
      raise exception 'No se pudo crear o reutilizar el ejercicio %.', exercise_name;
    end if;

    insert into public.routine_exercises (
      routine_id,
      exercise_id,
      order_index,
      target_sets,
      target_reps,
      notes
    )
    values (
      target_routine_id,
      exercise_id,
      coalesce((exercise_payload->>'orderIndex')::integer, exercise_order),
      nullif(exercise_payload->>'targetSets', '')::integer,
      nullif(exercise_payload->>'targetReps', ''),
      nullif(exercise_payload->>'notes', '')
    );
  end loop;
end;
$$;

create function public.save_routine_with_exercises(
  routine_title text,
  routine_description text,
  exercises_payload jsonb
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  new_routine_id uuid;
  current_user_id uuid := auth.uid();
begin
  if current_user_id is null then
    raise exception 'Debe iniciar sesión para guardar rutinas.';
  end if;

  if routine_title is null or btrim(routine_title) = '' then
    raise exception 'El título de la rutina es obligatorio.';
  end if;

  insert into public.routines (user_id, title, description)
  values (current_user_id, btrim(routine_title), nullif(btrim(coalesce(routine_description, '')), ''))
  returning id into new_routine_id;

  perform public._insert_routine_exercises(new_routine_id, exercises_payload);

  return new_routine_id;
end;
$$;

drop function if exists public.regenerate_routine_day(uuid, text, text, jsonb);

create function public.regenerate_routine_day(
  p_routine_id uuid,
  routine_title text,
  routine_description text,
  exercises_payload jsonb
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  current_user_id uuid := auth.uid();
  owner_id uuid;
begin
  if current_user_id is null then
    raise exception 'Debe iniciar sesión para regenerar una rutina.';
  end if;

  select user_id into owner_id from public.routines where id = p_routine_id;

  if owner_id is null then
    raise exception 'Rutina no encontrada.';
  end if;

  if owner_id <> current_user_id then
    raise exception 'No tienes permiso para modificar esta rutina.';
  end if;

  if routine_title is null or btrim(routine_title) = '' then
    raise exception 'El título de la rutina es obligatorio.';
  end if;

  update public.routines
  set title = btrim(routine_title),
      description = nullif(btrim(coalesce(routine_description, '')), '')
  where id = p_routine_id;

  delete from public.routine_exercises where routine_id = p_routine_id;

  perform public._insert_routine_exercises(p_routine_id, exercises_payload);
end;
$$;

-- Compatibility wrapper mirroring save_ai_routine's Spanish-keyed single-day payload.
drop function if exists public.regenerate_ai_routine_day(uuid, jsonb);

create function public.regenerate_ai_routine_day(p_routine_id uuid, p_routine jsonb)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  exercises_payload jsonb;
begin
  if p_routine is null or jsonb_typeof(p_routine) <> 'object' then
    raise exception 'Payload de rutina inválido.';
  end if;

  select coalesce(jsonb_agg(
    jsonb_build_object(
      'orderIndex', exercise_order,
      'name', btrim(coalesce(exercise_item->>'nombre', '')),
      'targetMuscle', btrim(coalesce(exercise_item->>'musculoObjetivo', '')),
      'equipment', btrim(coalesce(exercise_item->>'equipamiento', '')),
      'targetSets', exercise_item->>'seriesObjetivo',
      'targetReps', exercise_item->>'repeticionesObjetivo',
      'notes', exercise_item->>'notas'
    )
  ), '[]'::jsonb)
  into exercises_payload
  from jsonb_array_elements(coalesce(p_routine->'ejercicios', '[]'::jsonb))
  with ordinality as payload(exercise_item, exercise_order);

  perform public.regenerate_routine_day(
    p_routine_id,
    p_routine->>'titulo',
    p_routine->>'descripcion',
    exercises_payload
  );
end;
$$;

grant execute on function public.save_routine_with_exercises(text, text, jsonb) to authenticated;
grant execute on function public.regenerate_routine_day(uuid, text, text, jsonb) to authenticated;
grant execute on function public.regenerate_ai_routine_day(uuid, jsonb) to authenticated;

commit;


-- END supabase/migrations/20260709_regenerate_routine_day_rpc.sql

-- BEGIN supabase/migrations/20260710_add_mesociclos.sql

-- Mesociclos (Fase 8, ítem diferido sin diseño previo): programas de entrenamiento
-- de varias semanas con semanas de deload programadas.
--
-- Cada rutina guardada ya es la unidad atómica "día" (ver 20260706_consolidate_save_routine_rpc.sql)
-- y nunca se comparte entre programas/semanas, así que en vez de una tabla puente
-- muchos-a-muchos se agregan columnas nullable directamente a `routines` — mismo
-- patrón que `training_goal` etc. en `profiles` (20260707_add_persistent_profile_fields.sql)
-- y `owner_id` en `exercises` (20260706_separate_global_and_personal_exercises.sql):
-- sin relleno no cambia nada, cero backfill, y workout_logs.routine_id (on delete
-- set null) y los flujos de borrar/regenerar día quedan intactos porque solo tocan
-- routine_id.
--
-- La semana "actual" de un programa no se guarda: se deriva como
-- max(week_number) entre las rutinas del programa, para no tener un segundo
-- estado que pueda desincronizarse.
--
-- Regla de deload v1: cadencia fija configurable por programa
-- (deload_every_n_weeks). is_deload_week se calcula y persiste en el momento de
-- guardar la rutina (no se recalcula al leer), porque es un hecho sobre lo que
-- efectivamente se le pidió a Gemini que generara ese día. Deload automático por
-- tendencia de RPE queda explícitamente diferido a una iteración futura.

begin;

create table if not exists public.programs (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references public.profiles(id) on delete cascade not null,
  name text not null,
  focus text,
  duration_weeks integer not null check (duration_weeks between 1 and 16),
  days_per_week integer not null check (days_per_week between 1 and 7),
  deload_every_n_weeks integer,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.programs
  drop constraint if exists programs_deload_every_n_weeks_check,
  add constraint programs_deload_every_n_weeks_check check (
    deload_every_n_weeks is null or (deload_every_n_weeks between 2 and duration_weeks)
  );

alter table public.programs enable row level security;

drop policy if exists "Users can read own programs" on public.programs;
create policy "Users can read own programs"
on public.programs for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "Users can create own programs" on public.programs;
create policy "Users can create own programs"
on public.programs for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "Users can update own programs" on public.programs;
create policy "Users can update own programs"
on public.programs for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "Users can delete own programs" on public.programs;
create policy "Users can delete own programs"
on public.programs for delete
to authenticated
using (auth.uid() = user_id);

alter table public.routines
  add column if not exists program_id uuid references public.programs(id) on delete set null,
  add column if not exists week_number integer,
  add column if not exists day_of_week integer,
  add column if not exists is_deload_week boolean not null default false;

alter table public.routines
  drop constraint if exists routines_day_of_week_check,
  add constraint routines_day_of_week_check check (day_of_week is null or day_of_week between 1 and 7);

alter table public.routines
  drop constraint if exists routines_program_week_check,
  add constraint routines_program_week_check check (
    (program_id is null and week_number is null) or (program_id is not null and week_number is not null)
  );

create unique index if not exists routines_program_week_day_idx
on public.routines (program_id, week_number, day_of_week)
where program_id is not null;

-- Postgres identifica las funciones por su firma de tipos de argumento, no solo
-- por nombre: agregar 3 parámetros nuevos crearía una función sobrecargada
-- adicional en vez de reemplazar la de 3 argumentos si no se elimina primero
-- (mismo motivo por el que 20260709_regenerate_routine_day_rpc.sql hizo un drop
-- explícito antes de recrear con una firma distinta).
drop function if exists public.save_routine_with_exercises(text, text, jsonb);
drop function if exists public.save_routine_with_exercises(text, text, jsonb, uuid, integer, integer);

create function public.save_routine_with_exercises(
  routine_title text,
  routine_description text,
  exercises_payload jsonb,
  p_program_id uuid default null,
  p_week_number integer default null,
  p_day_of_week integer default null
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  new_routine_id uuid;
  current_user_id uuid := auth.uid();
  v_deload_every_n_weeks integer;
  v_duration_weeks integer;
  v_is_deload boolean := false;
begin
  if current_user_id is null then
    raise exception 'Debe iniciar sesión para guardar rutinas.';
  end if;

  if routine_title is null or btrim(routine_title) = '' then
    raise exception 'El título de la rutina es obligatorio.';
  end if;

  if p_program_id is not null then
    select deload_every_n_weeks, duration_weeks into v_deload_every_n_weeks, v_duration_weeks
    from public.programs
    where id = p_program_id and user_id = current_user_id;

    if not found then
      raise exception 'Programa no encontrado o no pertenece al usuario actual.';
    end if;

    if p_week_number is null or p_week_number < 1 or p_week_number > v_duration_weeks then
      raise exception 'Número de semana inválido para este programa.';
    end if;

    v_is_deload := v_deload_every_n_weeks is not null and (p_week_number % v_deload_every_n_weeks = 0);
  end if;

  insert into public.routines (user_id, title, description, program_id, week_number, day_of_week, is_deload_week)
  values (
    current_user_id,
    btrim(routine_title),
    nullif(btrim(coalesce(routine_description, '')), ''),
    p_program_id,
    p_week_number,
    p_day_of_week,
    v_is_deload
  )
  returning id into new_routine_id;

  perform public._insert_routine_exercises(new_routine_id, exercises_payload);

  return new_routine_id;
end;
$$;

create or replace function public.save_ai_routine(p_routine jsonb)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  exercises_payload jsonb;
begin
  if p_routine is null or jsonb_typeof(p_routine) <> 'object' then
    raise exception 'Payload de rutina inválido.';
  end if;

  select coalesce(jsonb_agg(
    jsonb_build_object(
      'orderIndex', exercise_order,
      'name', btrim(coalesce(exercise_item->>'nombre', '')),
      'targetMuscle', btrim(coalesce(exercise_item->>'musculoObjetivo', '')),
      'equipment', btrim(coalesce(exercise_item->>'equipamiento', '')),
      'targetSets', exercise_item->>'seriesObjetivo',
      'targetReps', exercise_item->>'repeticionesObjetivo',
      'notes', exercise_item->>'notas'
    )
  ), '[]'::jsonb)
  into exercises_payload
  from jsonb_array_elements(coalesce(p_routine->'ejercicios', '[]'::jsonb))
  with ordinality as payload(exercise_item, exercise_order);

  return public.save_routine_with_exercises(
    p_routine->>'titulo',
    p_routine->>'descripcion',
    exercises_payload,
    nullif(p_routine->>'programaId', '')::uuid,
    nullif(p_routine->>'numeroSemana', '')::integer,
    nullif(p_routine->>'diaSemana', '')::integer
  );
end;
$$;

grant execute on function public.save_routine_with_exercises(text, text, jsonb, uuid, integer, integer) to authenticated;
grant execute on function public.save_ai_routine(jsonb) to authenticated;

commit;


-- END supabase/migrations/20260710_add_mesociclos.sql

-- BEGIN supabase/migrations/20260711_add_routine_exercise_prescription.sql

-- Fase vNext 1 (ROADMAP.md): real prescription fields per routine exercise, so a
-- generated routine is actually trainable (rest, target RPE/RIR, tempo, movement
-- pattern, priority within the session, progression rule, substitution criteria)
-- instead of just sets/reps/notes. All columns are nullable so existing routines
-- keep working without backfill.

begin;

alter table public.routine_exercises
  add column if not exists rest_seconds integer,
  add column if not exists target_rpe numeric(3,1),
  add column if not exists target_rir numeric(3,1),
  add column if not exists tempo text,
  add column if not exists movement_pattern text,
  add column if not exists priority text,
  add column if not exists progression_rule text,
  add column if not exists substitution_criteria text;

alter table public.routine_exercises
  drop constraint if exists routine_exercises_target_rpe_check,
  add constraint routine_exercises_target_rpe_check
    check (target_rpe is null or target_rpe between 1 and 10),
  drop constraint if exists routine_exercises_target_rir_check,
  add constraint routine_exercises_target_rir_check
    check (target_rir is null or target_rir between 0 and 5),
  drop constraint if exists routine_exercises_rest_seconds_check,
  add constraint routine_exercises_rest_seconds_check
    check (rest_seconds is null or rest_seconds between 30 and 600),
  drop constraint if exists routine_exercises_priority_check,
  add constraint routine_exercises_priority_check
    check (priority is null or priority in ('principal', 'accesorio', 'aislamiento', 'correctivo')),
  drop constraint if exists routine_exercises_movement_pattern_check,
  add constraint routine_exercises_movement_pattern_check
    check (
      movement_pattern is null or movement_pattern in (
        'squat', 'hinge', 'horizontal_push', 'vertical_push',
        'horizontal_pull', 'vertical_pull', 'lunge', 'carry',
        'core', 'isolation', 'conditioning', 'mobility'
      )
    );

-- _insert_routine_exercises (20260709_regenerate_routine_day_rpc.sql) now reads the
-- 8 new optional keys from each exercise payload item. Signature is unchanged.
create or replace function public._insert_routine_exercises(
  target_routine_id uuid,
  exercises_payload jsonb
)
returns void
language plpgsql
set search_path = public
as $$
declare
  exercise_payload jsonb;
  exercise_id uuid;
  exercise_name text;
  exercise_target_muscle text;
  exercise_equipment text;
  exercise_order integer := 0;
begin
  if exercises_payload is null or jsonb_typeof(exercises_payload) <> 'array' or jsonb_array_length(exercises_payload) = 0 then
    raise exception 'La rutina debe incluir al menos un ejercicio.';
  end if;

  for exercise_payload in select value from jsonb_array_elements(exercises_payload)
  loop
    exercise_order := exercise_order + 1;
    exercise_name := btrim(coalesce(exercise_payload->>'name', ''));
    exercise_target_muscle := btrim(coalesce(exercise_payload->>'targetMuscle', ''));
    exercise_equipment := btrim(coalesce(exercise_payload->>'equipment', ''));

    if exercise_name = '' then
      raise exception 'El ejercicio % no tiene nombre.', exercise_order;
    end if;

    select id into exercise_id
    from public.exercises
    where lower(btrim(name)) = lower(btrim(exercise_name))
      and lower(btrim(target_muscle)) = lower(btrim(exercise_target_muscle))
      and lower(btrim(equipment)) = lower(btrim(exercise_equipment))
    limit 1;

    if exercise_id is null then
      begin
        insert into public.exercises (name, target_muscle, equipment)
        values (exercise_name, exercise_target_muscle, exercise_equipment)
        returning id into exercise_id;
      exception when unique_violation then
        select id into exercise_id
        from public.exercises
        where lower(btrim(name)) = lower(btrim(exercise_name))
          and lower(btrim(target_muscle)) = lower(btrim(exercise_target_muscle))
          and lower(btrim(equipment)) = lower(btrim(exercise_equipment))
        limit 1;
      end;
    end if;

    if exercise_id is null then
      raise exception 'No se pudo crear o reutilizar el ejercicio %.', exercise_name;
    end if;

    insert into public.routine_exercises (
      routine_id,
      exercise_id,
      order_index,
      target_sets,
      target_reps,
      notes,
      rest_seconds,
      target_rpe,
      target_rir,
      tempo,
      movement_pattern,
      priority,
      progression_rule,
      substitution_criteria
    )
    values (
      target_routine_id,
      exercise_id,
      coalesce((exercise_payload->>'orderIndex')::integer, exercise_order),
      nullif(exercise_payload->>'targetSets', '')::integer,
      nullif(exercise_payload->>'targetReps', ''),
      nullif(exercise_payload->>'notes', ''),
      nullif(exercise_payload->>'restSeconds', '')::integer,
      nullif(exercise_payload->>'targetRpe', '')::numeric,
      nullif(exercise_payload->>'targetRir', '')::numeric,
      nullif(exercise_payload->>'tempo', ''),
      nullif(exercise_payload->>'movementPattern', ''),
      nullif(exercise_payload->>'priority', ''),
      nullif(exercise_payload->>'progressionRule', ''),
      nullif(exercise_payload->>'substitutionCriteria', '')
    );
  end loop;
end;
$$;

-- save_ai_routine / regenerate_ai_routine_day (Spanish-keyed Gemini payload wrappers)
-- now also map the 8 new prescription fields into the English-keyed payload that
-- _insert_routine_exercises expects. save_ai_routine keeps forwarding the mesociclos
-- programaId/numeroSemana/diaSemana fields (20260710_add_mesociclos.sql) to the
-- 6-argument save_routine_with_exercises — dropping those here would silently
-- de-link every AI-generated routine from its program.
create or replace function public.save_ai_routine(p_routine jsonb)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  exercises_payload jsonb;
begin
  if p_routine is null or jsonb_typeof(p_routine) <> 'object' then
    raise exception 'Payload de rutina inválido.';
  end if;

  select coalesce(jsonb_agg(
    jsonb_build_object(
      'orderIndex', exercise_order,
      'name', btrim(coalesce(exercise_item->>'nombre', '')),
      'targetMuscle', btrim(coalesce(exercise_item->>'musculoObjetivo', '')),
      'equipment', btrim(coalesce(exercise_item->>'equipamiento', '')),
      'targetSets', exercise_item->>'seriesObjetivo',
      'targetReps', exercise_item->>'repeticionesObjetivo',
      'notes', exercise_item->>'notas',
      'restSeconds', exercise_item->>'descansoSegundos',
      'targetRpe', exercise_item->>'rpeObjetivo',
      'targetRir', exercise_item->>'rirObjetivo',
      'tempo', exercise_item->>'tempo',
      'movementPattern', exercise_item->>'patronMovimiento',
      'priority', exercise_item->>'prioridad',
      'progressionRule', exercise_item->>'reglaProgresion',
      'substitutionCriteria', exercise_item->>'criterioSustitucion'
    )
  ), '[]'::jsonb)
  into exercises_payload
  from jsonb_array_elements(coalesce(p_routine->'ejercicios', '[]'::jsonb))
  with ordinality as payload(exercise_item, exercise_order);

  return public.save_routine_with_exercises(
    p_routine->>'titulo',
    p_routine->>'descripcion',
    exercises_payload,
    nullif(p_routine->>'programaId', '')::uuid,
    nullif(p_routine->>'numeroSemana', '')::integer,
    nullif(p_routine->>'diaSemana', '')::integer
  );
end;
$$;

create or replace function public.regenerate_ai_routine_day(p_routine_id uuid, p_routine jsonb)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  exercises_payload jsonb;
begin
  if p_routine is null or jsonb_typeof(p_routine) <> 'object' then
    raise exception 'Payload de rutina inválido.';
  end if;

  select coalesce(jsonb_agg(
    jsonb_build_object(
      'orderIndex', exercise_order,
      'name', btrim(coalesce(exercise_item->>'nombre', '')),
      'targetMuscle', btrim(coalesce(exercise_item->>'musculoObjetivo', '')),
      'equipment', btrim(coalesce(exercise_item->>'equipamiento', '')),
      'targetSets', exercise_item->>'seriesObjetivo',
      'targetReps', exercise_item->>'repeticionesObjetivo',
      'notes', exercise_item->>'notas',
      'restSeconds', exercise_item->>'descansoSegundos',
      'targetRpe', exercise_item->>'rpeObjetivo',
      'targetRir', exercise_item->>'rirObjetivo',
      'tempo', exercise_item->>'tempo',
      'movementPattern', exercise_item->>'patronMovimiento',
      'priority', exercise_item->>'prioridad',
      'progressionRule', exercise_item->>'reglaProgresion',
      'substitutionCriteria', exercise_item->>'criterioSustitucion'
    )
  ), '[]'::jsonb)
  into exercises_payload
  from jsonb_array_elements(coalesce(p_routine->'ejercicios', '[]'::jsonb))
  with ordinality as payload(exercise_item, exercise_order);

  perform public.regenerate_routine_day(
    p_routine_id,
    p_routine->>'titulo',
    p_routine->>'descripcion',
    exercises_payload
  );
end;
$$;

commit;


-- END supabase/migrations/20260711_add_routine_exercise_prescription.sql

-- BEGIN supabase/migrations/20260712_add_readiness_logs.sql

-- Fase vNext 3 (ROADMAP.md): readiness check-in before training (energy, sleep,
-- soreness, joint pain, available time) so the session can be adapted without
-- regenerating the whole routine with AI. workout_log_id is nullable so a
-- readiness log can outlive/precede the session it was taken for, but in
-- practice the app always attaches it once the workout log exists.

begin;

create table public.readiness_logs (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references public.profiles(id) on delete cascade not null,
  workout_log_id uuid references public.workout_logs(id) on delete cascade,
  energy integer check (energy between 1 and 5),
  sleep_quality integer check (sleep_quality between 1 and 5),
  soreness integer check (soreness between 1 and 5),
  joint_pain boolean not null default false,
  available_minutes integer,
  notes text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.readiness_logs enable row level security;

create policy "Users can read own readiness logs"
on public.readiness_logs for select
to authenticated
using (auth.uid() = user_id);

create policy "Users can create own readiness logs"
on public.readiness_logs for insert
to authenticated
with check (auth.uid() = user_id);

commit;


-- END supabase/migrations/20260712_add_readiness_logs.sql

-- BEGIN supabase/migrations/20260713_add_mesocycle_phase_override.sql

-- Fase vNext 8 (resto, ROADMAP.md): lets the client force a week to be treated as
-- deload even off the fixed N-week cadence, driven by real fatigue/adherence
-- signals (Fase vNext 7 — src/lib/training/mesocycle.ts, shouldSuggestAdaptiveDeload)
-- instead of only the schedule. is_deload_week keeps reflecting what was actually
-- requested for that week (same rationale as 20260710_add_mesociclos.sql: no
-- second derived state that can desync), it just gains an optional override.
--
-- Postgres identifies functions by argument-type signature: adding a parameter
-- requires dropping the old signature first, same reasoning as every prior
-- signature change in this repo (20260709, 20260710).

begin;

drop function if exists public.save_routine_with_exercises(text, text, jsonb, uuid, integer, integer);

create function public.save_routine_with_exercises(
  routine_title text,
  routine_description text,
  exercises_payload jsonb,
  p_program_id uuid default null,
  p_week_number integer default null,
  p_day_of_week integer default null,
  p_force_deload boolean default null
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  new_routine_id uuid;
  current_user_id uuid := auth.uid();
  v_deload_every_n_weeks integer;
  v_duration_weeks integer;
  v_is_deload boolean := false;
begin
  if current_user_id is null then
    raise exception 'Debe iniciar sesión para guardar rutinas.';
  end if;

  if routine_title is null or btrim(routine_title) = '' then
    raise exception 'El título de la rutina es obligatorio.';
  end if;

  if p_program_id is not null then
    select deload_every_n_weeks, duration_weeks into v_deload_every_n_weeks, v_duration_weeks
    from public.programs
    where id = p_program_id and user_id = current_user_id;

    if not found then
      raise exception 'Programa no encontrado o no pertenece al usuario actual.';
    end if;

    if p_week_number is null or p_week_number < 1 or p_week_number > v_duration_weeks then
      raise exception 'Número de semana inválido para este programa.';
    end if;

    v_is_deload := coalesce(p_force_deload, v_deload_every_n_weeks is not null and (p_week_number % v_deload_every_n_weeks = 0));
  end if;

  insert into public.routines (user_id, title, description, program_id, week_number, day_of_week, is_deload_week)
  values (
    current_user_id,
    btrim(routine_title),
    nullif(btrim(coalesce(routine_description, '')), ''),
    p_program_id,
    p_week_number,
    p_day_of_week,
    v_is_deload
  )
  returning id into new_routine_id;

  perform public._insert_routine_exercises(new_routine_id, exercises_payload);

  return new_routine_id;
end;
$$;

-- Unchanged mapping from 20260711_add_routine_exercise_prescription.sql, just
-- threading through the new forzarDescarga field.
create or replace function public.save_ai_routine(p_routine jsonb)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  exercises_payload jsonb;
begin
  if p_routine is null or jsonb_typeof(p_routine) <> 'object' then
    raise exception 'Payload de rutina inválido.';
  end if;

  select coalesce(jsonb_agg(
    jsonb_build_object(
      'orderIndex', exercise_order,
      'name', btrim(coalesce(exercise_item->>'nombre', '')),
      'targetMuscle', btrim(coalesce(exercise_item->>'musculoObjetivo', '')),
      'equipment', btrim(coalesce(exercise_item->>'equipamiento', '')),
      'targetSets', exercise_item->>'seriesObjetivo',
      'targetReps', exercise_item->>'repeticionesObjetivo',
      'notes', exercise_item->>'notas',
      'restSeconds', exercise_item->>'descansoSegundos',
      'targetRpe', exercise_item->>'rpeObjetivo',
      'targetRir', exercise_item->>'rirObjetivo',
      'tempo', exercise_item->>'tempo',
      'movementPattern', exercise_item->>'patronMovimiento',
      'priority', exercise_item->>'prioridad',
      'progressionRule', exercise_item->>'reglaProgresion',
      'substitutionCriteria', exercise_item->>'criterioSustitucion'
    )
  ), '[]'::jsonb)
  into exercises_payload
  from jsonb_array_elements(coalesce(p_routine->'ejercicios', '[]'::jsonb))
  with ordinality as payload(exercise_item, exercise_order);

  return public.save_routine_with_exercises(
    p_routine->>'titulo',
    p_routine->>'descripcion',
    exercises_payload,
    nullif(p_routine->>'programaId', '')::uuid,
    nullif(p_routine->>'numeroSemana', '')::integer,
    nullif(p_routine->>'diaSemana', '')::integer,
    (p_routine->>'forzarDescarga')::boolean
  );
end;
$$;

grant execute on function public.save_routine_with_exercises(text, text, jsonb, uuid, integer, integer, boolean) to authenticated;
grant execute on function public.save_ai_routine(jsonb) to authenticated;

commit;


-- END supabase/migrations/20260713_add_mesocycle_phase_override.sql

-- BEGIN supabase/migrations/20260714_add_ai_generations.sql

-- Fase vNext 10 (ROADMAP.md): traceability for AI-generated content — model,
-- prompt/schema version, input/output, latency, success/error — so a bad prompt
-- can be identified and compared against prior versions. Only the 3 AI routes
-- that exist today are valid `type` values; extend the CHECK when new ones ship
-- (program_week_generation, exercise_substitution, coach_recommendation).

begin;

create table public.ai_generations (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references public.profiles(id) on delete set null,
  type text not null check (type in ('routine_generation', 'routine_regeneration', 'workout_insight')),
  model text not null,
  prompt_version text not null,
  schema_version text not null,
  input jsonb,
  output jsonb,
  latency_ms integer,
  success boolean not null default false,
  error text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.ai_generations enable row level security;

create policy "Users can read own ai generations"
on public.ai_generations for select
to authenticated
using (auth.uid() = user_id);

create policy "Users can create own ai generations"
on public.ai_generations for insert
to authenticated
with check (auth.uid() = user_id);

commit;


-- END supabase/migrations/20260714_add_ai_generations.sql

-- BEGIN supabase/migrations/20260715_add_exercise_catalog_curation.sql

-- Fase vNext 4, resto (ROADMAP.md): curated exercise catalog fields (canonical
-- name, aliases, movement pattern, difficulty, verified flag) plus a minimal
-- admin flag so /admin/exercises can exist without opening the shared global
-- catalog to any authenticated user. There is no admin concept anywhere else in
-- this app yet — profiles.is_admin defaults to false for everyone; the first
-- admin has to be flipped by hand (e.g. via the Supabase SQL editor), same as
-- any bootstrap-admin problem.

begin;

alter table public.profiles
  add column if not exists is_admin boolean not null default false;

alter table public.exercises
  add column if not exists canonical_name text,
  add column if not exists aliases text[] not null default '{}',
  add column if not exists movement_pattern text,
  add column if not exists difficulty text,
  add column if not exists is_verified boolean not null default false;

alter table public.exercises
  drop constraint if exists exercises_movement_pattern_check,
  add constraint exercises_movement_pattern_check check (
    movement_pattern is null or movement_pattern in (
      'squat', 'hinge', 'horizontal_push', 'vertical_push',
      'horizontal_pull', 'vertical_pull', 'lunge', 'carry',
      'core', 'isolation', 'conditioning', 'mobility'
    )
  );

alter table public.exercises
  drop constraint if exists exercises_difficulty_check,
  add constraint exercises_difficulty_check check (
    difficulty is null or difficulty in ('beginner', 'intermediate', 'advanced')
  );

-- Only admins can edit the global catalog (owner_id is null); nobody could
-- update `exercises` at all before this (20260706_restrict_direct_exercise_inserts.sql
-- removed the last direct-write policy). Personal exercises still have no update
-- path — no feature creates them yet.
create policy "Admins can update global exercises"
on public.exercises for update
to authenticated
using (
  owner_id is null
  and exists (select 1 from public.profiles where id = auth.uid() and is_admin)
)
with check (
  owner_id is null
  and exists (select 1 from public.profiles where id = auth.uid() and is_admin)
);

commit;


-- END supabase/migrations/20260715_add_exercise_catalog_curation.sql

-- BEGIN supabase/migrations/20260716_add_alias_matching.sql

-- Fase vNext 4, resto (ROADMAP.md): matches an incoming exercise name against the
-- curated `aliases` array too, not just an exact case-insensitive name match.
-- This is what actually closes the "Press banca" vs "Press de banca" vs "Barbell
-- bench press" duplication gap — but only once an admin has curated aliases via
-- /admin/exercises (20260715_add_exercise_catalog_curation.sql); until then this
-- is a no-op superset of the existing exact-match behavior.

begin;

create or replace function public._insert_routine_exercises(
  target_routine_id uuid,
  exercises_payload jsonb
)
returns void
language plpgsql
set search_path = public
as $$
declare
  exercise_payload jsonb;
  exercise_id uuid;
  exercise_name text;
  exercise_target_muscle text;
  exercise_equipment text;
  exercise_order integer := 0;
begin
  if exercises_payload is null or jsonb_typeof(exercises_payload) <> 'array' or jsonb_array_length(exercises_payload) = 0 then
    raise exception 'La rutina debe incluir al menos un ejercicio.';
  end if;

  for exercise_payload in select value from jsonb_array_elements(exercises_payload)
  loop
    exercise_order := exercise_order + 1;
    exercise_name := btrim(coalesce(exercise_payload->>'name', ''));
    exercise_target_muscle := btrim(coalesce(exercise_payload->>'targetMuscle', ''));
    exercise_equipment := btrim(coalesce(exercise_payload->>'equipment', ''));

    if exercise_name = '' then
      raise exception 'El ejercicio % no tiene nombre.', exercise_order;
    end if;

    select id into exercise_id
    from public.exercises
    where (
        lower(btrim(name)) = lower(btrim(exercise_name))
        or lower(btrim(exercise_name)) = any(select lower(btrim(alias)) from unnest(aliases) as alias)
      )
      and lower(btrim(target_muscle)) = lower(btrim(exercise_target_muscle))
      and lower(btrim(equipment)) = lower(btrim(exercise_equipment))
    limit 1;

    if exercise_id is null then
      begin
        insert into public.exercises (name, target_muscle, equipment)
        values (exercise_name, exercise_target_muscle, exercise_equipment)
        returning id into exercise_id;
      exception when unique_violation then
        select id into exercise_id
        from public.exercises
        where (
            lower(btrim(name)) = lower(btrim(exercise_name))
            or lower(btrim(exercise_name)) = any(select lower(btrim(alias)) from unnest(aliases) as alias)
          )
          and lower(btrim(target_muscle)) = lower(btrim(exercise_target_muscle))
          and lower(btrim(equipment)) = lower(btrim(exercise_equipment))
        limit 1;
      end;
    end if;

    if exercise_id is null then
      raise exception 'No se pudo crear o reutilizar el ejercicio %.', exercise_name;
    end if;

    insert into public.routine_exercises (
      routine_id,
      exercise_id,
      order_index,
      target_sets,
      target_reps,
      notes,
      rest_seconds,
      target_rpe,
      target_rir,
      tempo,
      movement_pattern,
      priority,
      progression_rule,
      substitution_criteria
    )
    values (
      target_routine_id,
      exercise_id,
      coalesce((exercise_payload->>'orderIndex')::integer, exercise_order),
      nullif(exercise_payload->>'targetSets', '')::integer,
      nullif(exercise_payload->>'targetReps', ''),
      nullif(exercise_payload->>'notes', ''),
      nullif(exercise_payload->>'restSeconds', '')::integer,
      nullif(exercise_payload->>'targetRpe', '')::numeric,
      nullif(exercise_payload->>'targetRir', '')::numeric,
      nullif(exercise_payload->>'tempo', ''),
      nullif(exercise_payload->>'movementPattern', ''),
      nullif(exercise_payload->>'priority', ''),
      nullif(exercise_payload->>'progressionRule', ''),
      nullif(exercise_payload->>'substitutionCriteria', '')
    );
  end loop;
end;
$$;

commit;


-- END supabase/migrations/20260716_add_alias_matching.sql

-- BEGIN supabase/migrations/20260717_add_offline_idempotency.sql

-- Idempotency columns for offline write support (vNext 14).
-- These nullable columns let the client assign a unique operation ID so the
-- API layer can detect duplicate inserts when retrying after a failed sync.
ALTER TABLE workout_logs ADD COLUMN IF NOT EXISTS client_operation_id text;

ALTER TABLE set_logs ADD COLUMN IF NOT EXISTS client_operation_id text;

ALTER TABLE readiness_logs ADD COLUMN IF NOT EXISTS client_operation_id text;


-- END supabase/migrations/20260717_add_offline_idempotency.sql

-- BEGIN supabase/migrations/20260718_add_user_exercise_preferences.sql

-- vNext 15 — Personalización avanzada: preferencias de ejercicios por usuario.
-- Cada fila captura si el usuario marcó un ejercicio como favorito o evitado,
-- cuántas veces lo ha usado y cuándo fue la última vez.
CREATE TABLE IF NOT EXISTS user_exercise_preferences (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  exercise_id uuid NOT NULL REFERENCES exercises(id) ON DELETE CASCADE,
  is_favorite boolean DEFAULT false,
  is_avoided boolean DEFAULT false,
  times_used integer DEFAULT 0,
  last_used_at timestamptz,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  UNIQUE(user_id, exercise_id)
);

ALTER TABLE user_exercise_preferences ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can manage own preferences"
  ON user_exercise_preferences FOR ALL
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);


-- END supabase/migrations/20260718_add_user_exercise_preferences.sql

-- BEGIN supabase/migrations/20260719_add_coach_recommendations.sql

-- vNext+ P0-1 (ROADMAP.md): Coach IA proactivo — persistir las recomendaciones que
-- buildWeeklyRecommendations() genera de forma efímera para mostrarlas proactivamente
-- en el Home con badge de no leídas.

begin;

create table public.coach_recommendations (
  id uuid default gen_random_uuid() primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  category text not null check (category in ('volume_low', 'volume_high', 'fatigue', 'adherence', 'general')),
  severity text not null check (severity in ('info', 'warning', 'critical')),
  message text not null,
  is_read boolean not null default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.coach_recommendations enable row level security;

create policy "Users can read own recommendations"
on public.coach_recommendations for select
to authenticated
using (auth.uid() = user_id);

create policy "Users can create own recommendations"
on public.coach_recommendations for insert
to authenticated
with check (auth.uid() = user_id);

create policy "Users can update own recommendations"
on public.coach_recommendations for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

commit;


-- END supabase/migrations/20260719_add_coach_recommendations.sql

-- BEGIN supabase/migrations/20260720_add_ai_feedback.sql

-- P1-4 (ROADMAP.md vNext+): User feedback on AI quality — thumbs up/down so
-- prompts can be iterated with real data instead of just latency/error metrics.

begin;

alter table public.ai_generations
add column if not exists user_feedback text
check (user_feedback is null or user_feedback in ('thumbs_up', 'thumbs_down'));

-- Admins can read all generations for audit (vNext 18, deferred)
create policy "Admins can read all ai generations"
on public.ai_generations for select
to authenticated
using (
  exists (select 1 from public.profiles where profiles.id = auth.uid() and profiles.is_admin = true)
);

-- All authenticated users can write feedback on their own generations
create policy "Users can update own ai generations feedback"
on public.ai_generations for update
to authenticated
using (auth.uid() = user_id)
with check (
  -- Only the user_feedback column may change
  auth.uid() = user_id
);

commit;


-- END supabase/migrations/20260720_add_ai_feedback.sql

-- BEGIN supabase/migrations/20260720_add_personal_records.sql

-- P1-3 (ROADMAP.md vNext+): Personal Records tracking — cada vez que un usuario
-- rompe su mejor marca histórica en peso, reps, volumen o 1RM estimado para un
-- ejercicio, se registra como PR para celebrarlo durante la sesión y mostrarlo
-- en el historial de progreso.

begin;

create table public.personal_records (
  id uuid default gen_random_uuid() primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  exercise_id uuid not null references public.exercises(id) on delete cascade,
  metric_type text not null check (metric_type in ('weight', 'reps', 'volume', 'one_rep_max')),
  value numeric(12,2) not null,
  workout_log_id uuid not null references public.workout_logs(id) on delete cascade,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.personal_records enable row level security;

create policy "Users can read own PRs"
on public.personal_records for select
to authenticated
using (auth.uid() = user_id);

create policy "Users can insert own PRs"
on public.personal_records for insert
to authenticated
with check (auth.uid() = user_id);

commit;


-- END supabase/migrations/20260720_add_personal_records.sql

-- BEGIN supabase/migrations/20260721_add_exercise_substitutions.sql

-- P2-6 (ROADMAP.md vNext+): Exercise substitution audit log — cuando un
-- usuario sustituye un ejercicio en plena sesión, este registro preserva el
-- historial de qué ejercicio fue reemplazado por cuál, en vez de perder el dato
-- con un simple UPDATE de routine_exercises.exercise_id.

begin;

create table public.exercise_substitutions (
  id uuid default gen_random_uuid() primary key,
  routine_exercise_id uuid not null references public.routine_exercises(id) on delete cascade,
  from_exercise_id uuid not null references public.exercises(id) on delete cascade,
  to_exercise_id uuid not null references public.exercises(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  workout_log_id uuid references public.workout_logs(id) on delete set null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.exercise_substitutions enable row level security;

create policy "Users can read own substitutions"
on public.exercise_substitutions for select
to authenticated
using (auth.uid() = user_id);

create policy "Users can insert own substitutions"
on public.exercise_substitutions for insert
to authenticated
with check (auth.uid() = user_id);

commit;


-- END supabase/migrations/20260721_add_exercise_substitutions.sql

-- BEGIN supabase/migrations/20260722_add_cardio_logs.sql

-- P3-12 (ROADMAP.md vNext+): Cardio y movilidad — registro de sesiones de
-- cardio (correr, bicicleta, natación, etc.) con métricas básicas.

begin;

create table public.cardio_logs (
  id uuid default gen_random_uuid() primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  type text not null check (type in ('running', 'cycling', 'walking', 'swimming', 'rowing', 'other')),
  duration_seconds integer not null check (duration_seconds > 0),
  distance_meters numeric(10,1),
  heart_rate_avg integer,
  calories integer,
  notes text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.cardio_logs enable row level security;

create policy "Users can read own cardio"
on public.cardio_logs for select
to authenticated
using (auth.uid() = user_id);

create policy "Users can insert own cardio"
on public.cardio_logs for insert
to authenticated
with check (auth.uid() = user_id);

create policy "Users can delete own cardio"
on public.cardio_logs for delete
to authenticated
using (auth.uid() = user_id);

commit;


-- END supabase/migrations/20260722_add_cardio_logs.sql

-- BEGIN supabase/migrations/20260723_add_cardio_planning_and_hr.sql

-- vNext++ U9 + U10 (ROADMAP.md): integrar el cardio al plan y habilitar zonas de
-- frecuencia cardíaca.
--   U9: el cardio deja de ser un cuaderno aislado — se puede asociar a un programa
--       (para que cuente en adherencia) y a la sesión de fuerza del mismo día.
--   U10: FC máxima por sesión + esfuerzo percibido; la FC máx del usuario (medida o
--       estimada por edad con birth_year) permite derivar zonas Z1-Z5 en el cliente.
-- Todas las columnas son nullable: los registros de cardio existentes siguen válidos.

begin;

alter table public.cardio_logs
  add column if not exists program_id uuid references public.programs(id) on delete set null,
  add column if not exists workout_log_id uuid references public.workout_logs(id) on delete set null,
  add column if not exists heart_rate_max integer,
  add column if not exists perceived_effort integer;

alter table public.cardio_logs
  drop constraint if exists cardio_logs_perceived_effort_check,
  add constraint cardio_logs_perceived_effort_check
    check (perceived_effort is null or perceived_effort between 1 and 10),
  drop constraint if exists cardio_logs_heart_rate_max_check,
  add constraint cardio_logs_heart_rate_max_check
    check (heart_rate_max is null or heart_rate_max between 60 and 240);

-- Para estimar FC máxima por edad (fórmula Tanaka: 208 - 0.7*edad) cuando el usuario
-- no mide su FC máx real. max_heart_rate permite un override manual medido en test.
alter table public.profiles
  add column if not exists birth_year integer,
  add column if not exists max_heart_rate integer;

alter table public.profiles
  drop constraint if exists profiles_birth_year_check,
  add constraint profiles_birth_year_check
    check (birth_year is null or birth_year between 1900 and 2025),
  drop constraint if exists profiles_max_heart_rate_check,
  add constraint profiles_max_heart_rate_check
    check (max_heart_rate is null or max_heart_rate between 120 and 240);

commit;


-- END supabase/migrations/20260723_add_cardio_planning_and_hr.sql

-- BEGIN supabase/migrations/20260723_add_nutrition_logs.sql

-- vNext++ U18 (ROADMAP.md): tracking mínimo de nutrición/hidratación diaria (agua,
-- proteína, calorías). Un registro por usuario y día (upsert on conflict), para
-- cerrar el círculo de coaching junto con peso corporal / body_measurements.

begin;

create table if not exists public.daily_nutrition_logs (
  id uuid default gen_random_uuid() primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  log_date date not null default (timezone('utc'::text, now())::date),
  water_ml integer check (water_ml is null or water_ml between 0 and 20000),
  protein_g numeric(5,1) check (protein_g is null or protein_g between 0 and 1000),
  calories integer check (calories is null or calories between 0 and 20000),
  notes text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique (user_id, log_date)
);

alter table public.daily_nutrition_logs enable row level security;

create policy "Users can read own nutrition"
on public.daily_nutrition_logs for select
to authenticated
using (auth.uid() = user_id);

create policy "Users can insert own nutrition"
on public.daily_nutrition_logs for insert
to authenticated
with check (auth.uid() = user_id);

create policy "Users can update own nutrition"
on public.daily_nutrition_logs for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "Users can delete own nutrition"
on public.daily_nutrition_logs for delete
to authenticated
using (auth.uid() = user_id);

commit;


-- END supabase/migrations/20260723_add_nutrition_logs.sql

-- BEGIN supabase/migrations/20260723_add_supersets_and_set_details.sql

-- vNext++ U13 + U11 + U16 (ROADMAP.md):
--   U13: supersets/dropsets — ejercicios que comparten superset_group se entrenan
--        como una superserie (A1/A2); set_style marca dropset/rest-pause/etc.
--   U11: logging coherente RPE/RIR — set_logs.rir permite registrar en RIR además
--        de RPE (la prescripción ya soportaba target_rir).
--   U16: tempo real (TUT) y unilateralidad — set_logs.tempo_seconds y side (both/
--        left/right) para registrar por lado y detectar asimetrías.
-- Todo nullable: rutinas y series existentes siguen válidas.

begin;

alter table public.routine_exercises
  add column if not exists superset_group integer,
  add column if not exists set_style text;

alter table public.routine_exercises
  drop constraint if exists routine_exercises_set_style_check,
  add constraint routine_exercises_set_style_check
    check (set_style is null or set_style in ('normal', 'dropset', 'rest_pause', 'myo_reps', 'amrap')),
  drop constraint if exists routine_exercises_superset_group_check,
  add constraint routine_exercises_superset_group_check
    check (superset_group is null or superset_group between 1 and 20);

alter table public.set_logs
  add column if not exists rir numeric(3,1),
  add column if not exists side text,
  add column if not exists tempo_seconds integer;

alter table public.set_logs
  drop constraint if exists set_logs_rir_check,
  add constraint set_logs_rir_check
    check (rir is null or rir between 0 and 5),
  drop constraint if exists set_logs_side_check,
  add constraint set_logs_side_check
    check (side is null or side in ('both', 'left', 'right')),
  drop constraint if exists set_logs_tempo_seconds_check,
  add constraint set_logs_tempo_seconds_check
    check (tempo_seconds is null or tempo_seconds between 1 and 600);

-- _insert_routine_exercises: extiende la versión con alias-matching (20260716) para
-- persistir también supersetGroup y setStyle. El resto de la lógica (matching por
-- alias, dedup, inserción de los 8 campos de prescripción) es idéntica.
create or replace function public._insert_routine_exercises(
  target_routine_id uuid,
  exercises_payload jsonb
)
returns void
language plpgsql
set search_path = public
as $$
declare
  exercise_payload jsonb;
  exercise_id uuid;
  exercise_name text;
  exercise_target_muscle text;
  exercise_equipment text;
  exercise_order integer := 0;
begin
  if exercises_payload is null or jsonb_typeof(exercises_payload) <> 'array' or jsonb_array_length(exercises_payload) = 0 then
    raise exception 'La rutina debe incluir al menos un ejercicio.';
  end if;

  for exercise_payload in select value from jsonb_array_elements(exercises_payload)
  loop
    exercise_order := exercise_order + 1;
    exercise_name := btrim(coalesce(exercise_payload->>'name', ''));
    exercise_target_muscle := btrim(coalesce(exercise_payload->>'targetMuscle', ''));
    exercise_equipment := btrim(coalesce(exercise_payload->>'equipment', ''));

    if exercise_name = '' then
      raise exception 'El ejercicio % no tiene nombre.', exercise_order;
    end if;

    select id into exercise_id
    from public.exercises
    where (
        lower(btrim(name)) = lower(btrim(exercise_name))
        or lower(btrim(exercise_name)) = any(select lower(btrim(alias)) from unnest(aliases) as alias)
      )
      and lower(btrim(target_muscle)) = lower(btrim(exercise_target_muscle))
      and lower(btrim(equipment)) = lower(btrim(exercise_equipment))
    limit 1;

    if exercise_id is null then
      begin
        insert into public.exercises (name, target_muscle, equipment)
        values (exercise_name, exercise_target_muscle, exercise_equipment)
        returning id into exercise_id;
      exception when unique_violation then
        select id into exercise_id
        from public.exercises
        where (
            lower(btrim(name)) = lower(btrim(exercise_name))
            or lower(btrim(exercise_name)) = any(select lower(btrim(alias)) from unnest(aliases) as alias)
          )
          and lower(btrim(target_muscle)) = lower(btrim(exercise_target_muscle))
          and lower(btrim(equipment)) = lower(btrim(exercise_equipment))
        limit 1;
      end;
    end if;

    if exercise_id is null then
      raise exception 'No se pudo crear o reutilizar el ejercicio %.', exercise_name;
    end if;

    insert into public.routine_exercises (
      routine_id,
      exercise_id,
      order_index,
      target_sets,
      target_reps,
      notes,
      rest_seconds,
      target_rpe,
      target_rir,
      tempo,
      movement_pattern,
      priority,
      progression_rule,
      substitution_criteria,
      superset_group,
      set_style
    )
    values (
      target_routine_id,
      exercise_id,
      coalesce((exercise_payload->>'orderIndex')::integer, exercise_order),
      nullif(exercise_payload->>'targetSets', '')::integer,
      nullif(exercise_payload->>'targetReps', ''),
      nullif(exercise_payload->>'notes', ''),
      nullif(exercise_payload->>'restSeconds', '')::integer,
      nullif(exercise_payload->>'targetRpe', '')::numeric,
      nullif(exercise_payload->>'targetRir', '')::numeric,
      nullif(exercise_payload->>'tempo', ''),
      nullif(exercise_payload->>'movementPattern', ''),
      nullif(exercise_payload->>'priority', ''),
      nullif(exercise_payload->>'progressionRule', ''),
      nullif(exercise_payload->>'substitutionCriteria', ''),
      nullif(exercise_payload->>'supersetGroup', '')::integer,
      nullif(exercise_payload->>'setStyle', '')
    );
  end loop;
end;
$$;

-- save_ai_routine / regenerate_ai_routine_day: mapean las claves nuevas en español
-- (grupoSuperserie, estiloSerie) además de las ya existentes. Conservan la firma
-- completa: forwarding de programaId/numeroSemana/diaSemana/forzarDescarga.
create or replace function public.save_ai_routine(p_routine jsonb)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  exercises_payload jsonb;
begin
  if p_routine is null or jsonb_typeof(p_routine) <> 'object' then
    raise exception 'Payload de rutina inválido.';
  end if;

  select coalesce(jsonb_agg(
    jsonb_build_object(
      'orderIndex', exercise_order,
      'name', btrim(coalesce(exercise_item->>'nombre', '')),
      'targetMuscle', btrim(coalesce(exercise_item->>'musculoObjetivo', '')),
      'equipment', btrim(coalesce(exercise_item->>'equipamiento', '')),
      'targetSets', exercise_item->>'seriesObjetivo',
      'targetReps', exercise_item->>'repeticionesObjetivo',
      'notes', exercise_item->>'notas',
      'restSeconds', exercise_item->>'descansoSegundos',
      'targetRpe', exercise_item->>'rpeObjetivo',
      'targetRir', exercise_item->>'rirObjetivo',
      'tempo', exercise_item->>'tempo',
      'movementPattern', exercise_item->>'patronMovimiento',
      'priority', exercise_item->>'prioridad',
      'progressionRule', exercise_item->>'reglaProgresion',
      'substitutionCriteria', exercise_item->>'criterioSustitucion',
      'supersetGroup', exercise_item->>'grupoSuperserie',
      'setStyle', exercise_item->>'estiloSerie'
    )
  ), '[]'::jsonb)
  into exercises_payload
  from jsonb_array_elements(coalesce(p_routine->'ejercicios', '[]'::jsonb))
  with ordinality as payload(exercise_item, exercise_order);

  return public.save_routine_with_exercises(
    p_routine->>'titulo',
    p_routine->>'descripcion',
    exercises_payload,
    nullif(p_routine->>'programaId', '')::uuid,
    nullif(p_routine->>'numeroSemana', '')::integer,
    nullif(p_routine->>'diaSemana', '')::integer,
    (p_routine->>'forzarDescarga')::boolean
  );
end;
$$;

create or replace function public.regenerate_ai_routine_day(p_routine_id uuid, p_routine jsonb)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  exercises_payload jsonb;
begin
  if p_routine is null or jsonb_typeof(p_routine) <> 'object' then
    raise exception 'Payload de rutina inválido.';
  end if;

  select coalesce(jsonb_agg(
    jsonb_build_object(
      'orderIndex', exercise_order,
      'name', btrim(coalesce(exercise_item->>'nombre', '')),
      'targetMuscle', btrim(coalesce(exercise_item->>'musculoObjetivo', '')),
      'equipment', btrim(coalesce(exercise_item->>'equipamiento', '')),
      'targetSets', exercise_item->>'seriesObjetivo',
      'targetReps', exercise_item->>'repeticionesObjetivo',
      'notes', exercise_item->>'notas',
      'restSeconds', exercise_item->>'descansoSegundos',
      'targetRpe', exercise_item->>'rpeObjetivo',
      'targetRir', exercise_item->>'rirObjetivo',
      'tempo', exercise_item->>'tempo',
      'movementPattern', exercise_item->>'patronMovimiento',
      'priority', exercise_item->>'prioridad',
      'progressionRule', exercise_item->>'reglaProgresion',
      'substitutionCriteria', exercise_item->>'criterioSustitucion',
      'supersetGroup', exercise_item->>'grupoSuperserie',
      'setStyle', exercise_item->>'estiloSerie'
    )
  ), '[]'::jsonb)
  into exercises_payload
  from jsonb_array_elements(coalesce(p_routine->'ejercicios', '[]'::jsonb))
  with ordinality as payload(exercise_item, exercise_order);

  perform public.regenerate_routine_day(
    p_routine_id,
    p_routine->>'titulo',
    p_routine->>'descripcion',
    exercises_payload
  );
end;
$$;

commit;


-- END supabase/migrations/20260723_add_supersets_and_set_details.sql
